source 'https://rubygems.org' do
  gem 'activesupport'
  gem 'ca_datafactory', branch: 'master', git: 'https://ca_regression:8n-imvzFS4zSd6-eRhvW@gitlab.com/daxko/club-automation/ca-test/ca_datafactory.git'
  gem 'certified'
	gem 'colorize'
  gem 'configatron'
  gem 'faker'
  gem 'glados', branch: 'master', git: 'https://ca_regression:e78pB46uQTze5937aLWj@gitlab.com/daxko/test/glados_gem.git'
  gem 'headless'
  gem 'httparty'
  gem 'json'
  gem 'json-schema'
  gem 'money'
  gem 'mysql2'
  gem 'parallel_tests', '2.14.1'
  gem 'php-serialize', '1.2'
  gem 'pry'
  gem 'pry-doc'
	gem 'page-object', '2.2.4'
  gem 'rest-client'
  gem 'rspec'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'rspec-collection_matchers', '~> 1.1'
  gem 'sequel'
  gem 'systemu'
  gem 'watir', '6.16'
  gem 'watir-dom-wait'
  gem 'win32-security'
end
